package com.hf.test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import com.hf.bean.Emp;

public class TestJDBC {
	public static void main(String[] args) throws Exception {
		Class.forName("");
		Connection conn= DriverManager.getConnection("", "", "");
		//autoGeneratedKeys 值1 表示    允许他自动生成id 
		PreparedStatement ps = conn.prepareStatement("insert into emp values(null,?,?,?)",1);
		ps.setString(1, "root");
		ps.setString(2, "26");
		ps.setString(3, "男");
		ps.executeUpdate();
		ResultSet rs = ps.getGeneratedKeys();
		rs.next();
		int i = rs.getInt(1);
		
		
		Statement statement = conn.createStatement();
		Emp emp = new Emp(null , "dd", 15, "男");
		statement.executeQuery("insert into emp values(null,'"+emp.getEname()+"','"+emp.getAge()+"','"+emp.getSex()+"')");
		//获取参数值的两种方式
	}
}
