spring:
  application:
    name: spring-src-demo

  datasource:
    url: jdbc:mysql://localhost:3306/app-management-test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    driver-class-name: com.mysql.jdbc.Driver
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 9